[package]
name = "docvault-storage"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
docvault-ooxml = { path = "../ooxml" }
docvault-types = { path = "../../shared/types" }
rusqlite = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
