<script setup lang="ts">
import { ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import BaseModal from "./BaseModal.vue";
import { useDialogs } from "../composables/useDialogs";
import { useVault } from "../composables/useVault";
import { useDesktopState } from "../composables/useDesktopState";
import { useActivityLog } from "../composables/useActivityLog";

/*
 * New-document dialog. Creates a blank document from an embedded empty
 * template (no user-supplied file): txt/md are empty files, docx/xlsx/pptx are
 * minimal-but-valid OOXML packages generated by the backend. Fed through the
 * same two-phase commit pipeline as AddDocumentDialog, so the snapshot/find/
 * baseline sequence mirrors it. When opened from a project's kebab menu, the
 * new doc is assigned to that project; from the all-documents kebab it gets no
 * project membership.
 */

const { t } = useI18n();
const { log } = useActivityLog();
const { newDocumentOpen, newDocumentProjectId, closeNewDocument } = useDialogs();
const { createBlankDocument, documents, loadDocuments, libraryPath } =
  useVault();
const desktop = useDesktopState();

/** Formats the backend can generate a blank source for. */
const FORMATS = ["txt", "md", "docx", "xlsx", "pptx"] as const;
type BlankFormat = (typeof FORMATS)[number];

const name = ref("");
const format = ref<BlankFormat>("docx");
const error = ref("");
const submitting = ref(false);
// Tracks whether the dialog is closing because the work was submitted, so a
// user-initiated close (cancel) logs `actionCancelled` but a post-submit close
// does not.
const submitted = ref(false);

watch(newDocumentOpen, (open) => {
  if (!open) return;
  name.value = "";
  format.value = "docx";
  error.value = "";
  submitting.value = false;
  submitted.value = false;
  log(
    t("log.actionRequested", {
      action: t("actionLogs.newDocument"),
      name: t("log.noDocument"),
      version: t("log.latest"),
    }),
  );
});

async function submit() {
  const resolvedName = name.value.trim();
  if (!resolvedName || submitting.value) return;
  submitting.value = true;
  error.value = "";
  try {
    // Snapshot the doc ids before the create so we can identify the freshly
    // created document once Phase A resolves (mirrors AddDocumentDialog).
    const snapshotIds = documents.value.map((d) => d.id);
    // Phase A runs synchronously inside createBlankDocument(): the new document
    // + its library copy (materialized from the embedded blank template) exist
    // once this resolves, so reload and baseline the working copy immediately.
    // The returned id is the Phase B archive job (compress), which surfaces in
    // the task bubble.
    await createBlankDocument({ name: resolvedName, format: format.value });
    await loadDocuments();
    const created =
      documents.value.find(
        (d) => !snapshotIds.includes(d.id) && d.name === resolvedName,
      ) ?? documents.value.find((d) => !snapshotIds.includes(d.id));
    if (created) {
      const libPath = await libraryPath({ document_id: created.id });
      const baseline = await desktop.probeAndBaseline(created.id, libPath);
      desktop.setTracked(baseline);
      // Assign to the originating project when the kebab was on a project row.
      const projectId = newDocumentProjectId.value;
      if (projectId) desktop.assignDocumentToProject(created.id, projectId);
    }
    submitted.value = true;
    log(t("log.documentCreated", { name: resolvedName }));
    closeNewDocument();
  } catch (e) {
    error.value = String(e);
    log(
      t("log.actionFailed", {
        action: t("actionLogs.newDocument"),
        error: String(e),
      }),
    );
  } finally {
    submitting.value = false;
  }
}

function close() {
  if (!submitted.value) {
    log(t("log.actionCancelled", { action: t("actionLogs.newDocument") }));
  }
  closeNewDocument();
}
</script>

<template>
  <BaseModal
    :open="newDocumentOpen"
    :title="t('newDocument.title')"
    :subtitle="t('newDocument.subtitle')"
    @close="close"
  >
    <form id="new-document-form" class="dialog-form" @submit.prevent="submit">
      <label class="field">
        <span>{{ t("newDocument.formatLabel") }}</span>
        <select v-model="format" class="text-input">
          <option v-for="f in FORMATS" :key="f" :value="f">
            {{ t(`newDocument.formats.${f}`) }}
          </option>
        </select>
      </label>

      <label class="field">
        <span>{{ t("newDocument.nameLabel") }}</span>
        <input
          v-model="name"
          type="text"
          class="text-input"
          :placeholder="t('newDocument.namePlaceholder')"
        />
      </label>

      <p v-if="error" class="form-error">{{ error }}</p>
    </form>

    <template #footer>
      <button class="secondary" type="button" @click="close">
        {{ t("actions.cancel") }}
      </button>
      <button
        class="primary"
        type="submit"
        form="new-document-form"
        :disabled="!name.trim() || submitting"
      >
        {{ t("newDocument.submit") }}
      </button>
    </template>
  </BaseModal>
</template>

<style scoped>
.dialog-form {
  display: grid;
  gap: 14px;
}

.field {
  display: grid;
  gap: 4px;
  min-width: 0;
}

.field span {
  color: var(--text-muted);
  font-size: 12px;
}

.text-input {
  height: 32px;
  padding: 0 10px;
  border: 1px solid var(--border-strong);
  border-radius: var(--radius-sm);
  background: var(--bg-surface);
  color: var(--text-primary);
  font-size: 13px;
}

select.text-input {
  padding-right: 28px;
}

.form-error {
  margin: 0;
  color: var(--danger-text);
  font-size: 13px;
}
</style>
