[package]
name = "docvault-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
docvault-ooxml = { path = "../ooxml" }
docvault-storage = { path = "../storage" }
docvault-types = { path = "../../shared/types" }
thiserror = { workspace = true }
tracing = { workspace = true }
