[package]
name = "docvault"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "docvault"
path = "src/main.rs"

[dependencies]
docvault-core = { path = "../../crates/core" }
docvault-storage = { path = "../../crates/storage" }
docvault-types = { path = "../../shared/types" }
serde_json = { workspace = true }
