[package]
name = "docvault"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "docvault"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
docvault-core = { path = "../../crates/core" }
docvault-storage = { path = "../../crates/storage" }
docvault-types = { path = "../../shared/types" }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
tempfile = { workspace = true }
